### ISSUE TITLE
Removing old content views with Ansible 2.9 rc5

### ISSUE THREAD

**Issue by harrydevine** [ahuffman/ansible-satellite6_manage_content_views#5]
My system got updated to Ansible 2.9rc5 and this role stopped working.  It would quit in build_cv_keep_list.yml on the "Set content view remove list" step.  The error shown was:

{
    "msg": "Unexpected templating type error occurred on ({{ cv_ver_names | difference(cv_keep_list) }}): coercing to Unicode: need string or buffer, dict found",
    "_ansible_no_log": false
}

I downgraded to Ansible 2.8.6 and the role began working again.

**Comment by ahuffman** [comment]
Thank you for reporting this issue.  Sorry it's taken me years to respond, I no longer had an environment to test against, so therefore I couldn't do much to correct.  I think the community here has a fix incoming via #6 .

**Comment by ahuffman** [comment]
Fixed with #6.

Version 1.0.5 is now live: https://galaxy.ansible.com/ahuffman/satellite6_manage_content_views
